export const mapStudentProfileResponseToForm = (profile) => ({
    email: profile?.email || "",
    name: profile?.name || "",
    surname: profile?.surname || "",
    password: "",
    passwordConfirm: "",
    patronymic: profile?.patronymic || "",
    birthdayDate: profile?.birthdayDate ? profile.birthdayDate.slice(0, 10) : "",
    phone: profile?.phone || "",
    vkLink: profile?.vkLink || "",
    tgLink: profile?.tgLink || "",
    maxLink: profile?.maxLink || "",
    githubLink: profile?.githubLink || "",
    university: profile?.university || "",
    specialization: profile?.specialization || "",
    graduationYear: profile?.graduationYear || "",
});

export const mapStudentProfileFormToDto = (formData) => ({
    email: formData.email,
    name: formData.name,
    surname: formData.surname,
    password: formData.password,
    passwordConfirm: formData.passwordConfirm,
    patronymic: formData.patronymic,
    birthdayDate: formData.birthdayDate || null,
    phone: formData.phone,
    vkLink: formData.vkLink,
    tgLink: formData.tgLink,
    maxLink: formData.maxLink,
    githubLink: formData.githubLink,
    university: formData.university,
    specialization: formData.specialization,
    graduationYear: formData.graduationYear ? Number(formData.graduationYear) : null,
});
